INSERT INTO CURRICULUMVITAE VALUES ( 101 ,'' ,'Aaron Oeder' , '' ,'' , '' ,'' ,4 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 102 ,'' ,'Aaron Metcalfe' , '' ,'' , '' ,'indeed.com/r/Aaron-Metcalfe/a66b84d6dd167c8e' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 103 ,'' ,'Abdul Samad Sindhi' , '' ,'' , '' ,'indeed.com/r/Abdul-Samad-Sindhi/7f5e301cd57870e3' ,12 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 104 ,'' ,'Abhimanyu Jha' , '' ,'' , '' ,'' ,8 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 105 ,'' ,'Abhinav kumar Labhishetty' , '' ,'' , '' ,'indeed.com/r/Abhinav-kumar-Labhishetty/d7e37f24275e1dc5' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 106 ,'' ,'Abimbola Apara-Awujoola' , '' ,'' , '' ,'' ,4 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 107 ,'' ,'Afifa Lodhi' , '' ,'' , '' ,'indeed.com/r/Afifa-Lodhi/207d8638db229f6e' ,6 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 108 ,'' ,'Agostinho Henriques' , '' ,'' , '' ,'' ,8 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 109 ,'' ,'Akanksha Arora' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 110 ,'' ,'' , '' ,'' , '' ,'indeed.com/r/Akhil-K/9ad62d53e20f9b56' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 111 ,'' ,'Akshay Khanna' , '' ,'' , '' ,'indeed.com/r/Akshay-Khanna/ba7f589c6e878396' ,4 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 112 ,'' ,'Ala Altaweel' , '' ,'' , '' ,'' ,2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 113 ,'' ,'Alan Jones' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 114 ,'' ,'Alan Truelove' , '' ,'' , '' ,'' ,8 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 115 ,'' ,'Alex Deryugin' , '' ,'' , '' ,'' ,20 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 116 ,'' ,'Alex Xie' , '' ,'' , '' ,'' ,2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 117 ,'' ,'Alexander Lashchenko' , '' ,'' , '' ,'indeed.com/r/Alexander-Lashchenko/c307cdd560e23d2c' ,6 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 118 ,'' ,'Alexandria Nelson' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 119 ,'' ,'Allen Green' , '' ,'' , '' ,'' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 120 ,'' ,'Amro Ibrahim' , '' ,'' , '' ,'indeed.com/r/Amro-Ibrahim/3c5fbc99773dae84' ,4 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 121 ,'' ,'Andrea Garrett MBA' , '' ,'' , '' ,'indeed.com/r/f1aa3cd206e96911' ,2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 122 ,'' ,'Andres-Flores' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 123 ,'' ,'Andrew Harrison' , '' ,'' , '' ,'indeed.com/r/Andrew-Harrison/a0209779e47be012' ,19 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 124 ,'' ,'Andrew Reed' , '' ,'' , '' ,'' ,2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 125 ,'' ,'Andrew Stokinger' , '' ,'' , '' ,'indeed.com/r/Andrew-Stokinger/7f9b587e7bb9df67' ,5 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 126 ,'' ,'Andrew Szczepanski' , '' ,'' , '' ,'indeed.com/r/Andrew-Szczepanski/f10df0bb09ad282c' ,11 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 127 ,'' ,'Andrew Wirtz' , '' ,'' , '' ,'' ,6 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 128 ,'' ,'Aniruddha Patel' , '' ,'' , '' ,'indeed.com/r/Aniruddha-Patel/bde5b28d58516766' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 129 ,'' ,'Aniruddha Tekade' , '' ,'' , '' ,'' ,2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 130 ,'' ,'Anjum Faraz' , '' ,'' , '' ,'' ,4 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 131 ,'' ,'Anna Chavez' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 132 ,'' ,'Anna Lorenza' , '' ,'' , '' ,'' ,2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 133 ,'' ,'Anthony Taylor Senior' , '' ,'' , '' ,'' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 134 ,'' ,'' , '' ,'' , '' ,'' ,11 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 135 ,'' ,'Antonio Johnson' , '' ,'' , '' ,'indeed.com/r/Antonio-Johnson/5e74af49f646c2a1' ,3 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 136 ,'' ,'Antony Gilbert' , '' ,'' , '' ,'indeed.com/r/Antony-Gilbert/c1cf393c3c4bb9e0' ,2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 137 ,'' ,'Anuradha Pothannagaari' , '' ,'' , '' ,'' ,2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 138 ,'' ,'Arthur Collins' , '' ,'' , '' ,'' ,35 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 139 ,'' ,'ArunaSindhu-Gorantla' , '' ,'' , '' ,'indeed.com/r/ArunaSindhu-Gorantla/f509ca2c6cbed8ab' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 140 ,'' ,'Ashok Mushannavar' , '' ,'' , '' ,'indeed.com/r/Ashok-Mushannavar/c0f6955ac888f6e5' ,-2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 141 ,'' ,'Aslam Aftabuddin' , '' ,'' , '' ,'indeed.com/r/Aslam-Aftabuddin/34d5b341962259dd' ,2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 142 ,'' ,'Asmamaw Mekuriaw' , '' ,'' , '' ,'' ,9 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 143 ,'' ,'Ben John' , '' ,'' , '' ,'indeed.com/r/Ben-John-Dela-Cruz/05c883da59bc2dd6' ,24 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 144 ,'' ,'Benjamin Davis' , '' ,'' , '' ,'' ,9 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 145 ,'' ,'Benjamin Mariadas' , '' ,'' , '' ,'indeed.com/r/Benjamin-Mariadas/9edf8503c030f089' ,7 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 146 ,'' ,'Benjamin Parker' , '' ,'' , '' ,'indeed.com/r/Benjamin-Parker/29e8fd8f814c68a8' ,5 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 147 ,'' ,'Bhanu iOS' , '' ,'' , '' ,'indeed.com/r/Bhanu-iOS/094b5c859d8c163f' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 148 ,'' ,'Binit Patel' , '' ,'' , '' ,'' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 149 ,'' ,'Biruk Duguma' , '' ,'' , '' ,'' ,2 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 150 ,'' ,'Bobby Kingsada' , '' ,'' , '' ,'' ,5 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 151 ,'' ,'Braden Joe' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 152 ,'' ,'Brandon Kalashian' , '' ,'' , '' ,'indeed.com/r/Brandon-Kalashian/dfd4ea794f669541' ,5 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 153 ,'' ,'Social Care Bristol' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 154 ,'' ,'Brent Sandstrom' , '' ,'' , '' ,'' ,6 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 155 ,'' ,'Brett Wyrick' , '' ,'' , '' ,'' ,5 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 156 ,'' ,'Calin Teodorescu' , '' ,'' , '' ,'' ,5 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 157 ,'' ,'Cameron Washak' , '' ,'' , '' ,'' ,13 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 158 ,'' ,'Candice Winston' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 159 ,'' ,'Carl Bales' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 160 ,'' ,'Carlos Jarmon' , '' ,'' , '' ,'' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 161 ,'' ,'Carlos Mayo' , '' ,'' , '' ,'indeed.com/r/Carlos-Mayo/03aee4fff1b9007e' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 162 ,'' ,'Carson Gedeus' , '' ,'' , '' ,'' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 163 ,'' ,'Chad Cashman' , '' ,'' , '' ,'indeed.com/r/Chad-Cashman/5e95994a0f46b2e1' ,5 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 164 ,'' ,'Chaitanya Ponnapalli' , '' ,'' , '' ,'indeed.com/r/Chaitanya-Ponnapalli/11841769b6decf17' ,3 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 165 ,'' ,'Chandra Dronadula' , '' ,'' , '' ,'' ,6 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 166 ,'' ,'Charles J. Buynovsky' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 167 ,'' ,'Chef Jones' , '' ,'' , '' ,'indeed.com/r/Chef-Jones/0760d8cdcc5af273' ,5 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 168 ,'' ,'Chencheng Shao' , '' ,'' , '' ,'indeed.com/r/Chencheng-Shao/0f01ac4ce660ca50' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 169 ,'' ,'Christopher Callahan' , '' ,'' , '' ,'' ,6 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 170 ,'' ,'Christopher Cooper' , '' ,'' , '' ,'indeed.com/r/Christopher-Cooper/5032d75fcbcd3ede' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 171 ,'' ,'Christopher Hope' , '' ,'' , '' ,'' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 172 ,'' ,'Christopher Matthews' , '' ,'' , '' ,'indeed.com/r/Christopher-Matthews/1bf1cec7077085a0' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 173 ,'' ,'Christy Wang' , '' ,'' , '' ,'' ,4 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 174 ,'' ,'Clement Causse' , '' ,'' , '' ,'' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 175 ,'' ,'Connor Hendrix' , '' ,'' , '' ,'indeed.com/r/Connor-Hendrix/e2904c6e9c633976' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 176 ,'' ,'Cosmin Cristian Şendroiu' , '' ,'' , '' ,'indeed.com/r/Cosmin-Cristian-Sendroiu/01a0fd785ac3de23' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 177 ,'' ,'Cristian Avalos' , '' ,'' , '' ,'indeed.com/r/Cristian-Avalos/7050546cc5893bfe' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 178 ,'' ,'Daniel Long' , '' ,'' , '' ,'indeed.com/r/Daniel-Long/303509f964ac052f' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 179 ,'' ,'Danilo Bassi' , '' ,'' , '' ,'indeed.com/r/Danilo-Bassi/2fbabd1c8781eb40' ,1 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 180 ,'' ,'David Beattie' , '' ,'' , '' ,'indeed.com/r/David-Beattie/e1493e7e34891caf' ,29 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 181 ,'' ,'David John' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 182 ,'' ,'David Miranda' , '' ,'' , '' ,'indeed.com/r/David-Miranda/628f14cd38b63370' ,6 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 183 ,'' ,'David Ray' , '' ,'' , '' ,'indeed.com/r/David-Ray/b36214e17fbd69b7' ,8 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 184 ,'' ,'David Rojas' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 185 ,'' ,'David Warner' , '' ,'' , '' ,'indeed.com/r/David-Warner/caede1e0a4d19da6' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 186 ,'' ,'Dawit Tewelde' , '' ,'' , '' ,'indeed.com/r/Dawit-Tewelde/62b2490e4d29ecf1' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 187 ,'' ,'Ding Zou' , '' ,'' , '' ,'' ,6 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 188 ,'' ,'Dipendra Kusi' , '' ,'' , '' ,'' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 189 ,'' ,'Do Om' , '' ,'' , '' ,'indeed.com/r/Do-Om/c256de797c6d9e40' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 190 ,'' ,'Donna Sander' , '' ,'' , '' ,'' ,11 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 191 ,'' ,'Duy Nguyen' , '' ,'' , '' ,'indeed.com/r/Duy-Nguyen/9f4d3f6adc887f43' ,15 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 192 ,'' ,'Edward Guo' , '' ,'' , '' ,'' ,3 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 193 ,'' ,'Elaine Kymes' , '' ,'' , '' ,'indeed.com/r/Elaine-Kymes/78fe0e2e4887df9e' ,4 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 194 ,'' ,'Eleanor Dawson' , '' ,'' , '' ,'indeed.com/r/Eleanor-Dawson/6f6eb06b877aefe4' ,0 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 195 ,'' ,'Chouka Endrit' , '' ,'' , '' ,'' ,3 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 196 ,'' ,'Erik Larsen' , '' ,'' , '' ,'' ,6 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 197 ,'' ,'Erin San Juan' , '' ,'' , '' ,'' ,9 ,'');
INSERT INTO CURRICULUMVITAE VALUES ( 198 ,'' ,'' , '' ,'' , '' ,'indeed.com/r/Felixnando-Meraz/efedd59f8db1ca8b' ,0 ,'');
INSERT INTO EXPERIENCE VALUES ( 101 ,'Software Developer' ,4 ,1599);
INSERT INTO EXPERIENCE VALUES ( 101 ,'PC Support Intern' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 103 ,'Teacher of Science' ,7 ,7);
INSERT INTO EXPERIENCE VALUES ( 103 ,'Assistant Teacher' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 103 ,'Assistant Teacher' ,2 ,2);
INSERT INTO EXPERIENCE VALUES ( 103 ,'Principal Incharge' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 103 ,'Head Teacher' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 103 ,'Science and Maths Teacher' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 103 ,'Assistant Teacher' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 104 ,'Software Developer' ,2 ,1597);
INSERT INTO EXPERIENCE VALUES ( 104 ,'Associate Software Developer/ Software Developer II' ,3 ,1598);
INSERT INTO EXPERIENCE VALUES ( 104 ,'Software Developer/Data Analyst' ,2 ,1597);
INSERT INTO EXPERIENCE VALUES ( 104 ,'Information Technology Intern' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 106 ,'IT Consultant' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 107 ,'Lecturer Computer Science' ,2 ,2);
INSERT INTO EXPERIENCE VALUES ( 107 ,'Lecturer Computer Science' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 108 ,'Software Engineer' ,8 ,1658);
INSERT INTO EXPERIENCE VALUES ( 110 ,'Java Developer' ,1 ,1451);
INSERT INTO EXPERIENCE VALUES ( 110 ,'Team Leader' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 110 ,'Team Leader' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 111 ,'Postgraduate Computer Scientist from a Redbrick University' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 112 ,'Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 112 ,'Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 114 ,'Software Developer' ,3 ,1598);
INSERT INTO EXPERIENCE VALUES ( 114 ,'Software Developer' ,0 ,1595);
INSERT INTO EXPERIENCE VALUES ( 114 ,'Software Developer' ,3 ,1598);
INSERT INTO EXPERIENCE VALUES ( 114 ,'Software Developer' ,2 ,1597);
INSERT INTO EXPERIENCE VALUES ( 115 ,'Senior Software Engineer' ,8 ,1658);
INSERT INTO EXPERIENCE VALUES ( 115 ,'Software Engineer' ,9 ,1659);
INSERT INTO EXPERIENCE VALUES ( 115 ,'Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 115 ,'Software Engineer' ,2 ,1652);
INSERT INTO EXPERIENCE VALUES ( 116 ,'iOS Developer' ,1 ,871);
INSERT INTO EXPERIENCE VALUES ( 116 ,'SERIOUS TECHNOLOGY' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 117 ,'Software QA Engineer' ,3 ,1653);
INSERT INTO EXPERIENCE VALUES ( 117 ,'Beta Tester' ,-2 ,-2);
INSERT INTO EXPERIENCE VALUES ( 117 ,'free-to-play developer and publisher' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 117 ,'Junior QA Engineer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 119 ,'on-call personal chef duties / Personal Chef' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 119 ,'Chef/Owner' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 120 ,'Senior Software Engineer' ,0 ,1650);
INSERT INTO EXPERIENCE VALUES ( 120 ,'Senior Software Engineer' ,2 ,1652);
INSERT INTO EXPERIENCE VALUES ( 120 ,'Software Engineer' ,2 ,1652);
INSERT INTO EXPERIENCE VALUES ( 121 ,'IT Service Management Analyst and Consultant' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 121 ,'Performed technical tasks that encompass Tier II system support' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 121 ,'PESG' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 123 ,'Database Administrator' ,5 ,12);
INSERT INTO EXPERIENCE VALUES ( 123 ,'Database Administrator' ,7 ,14);
INSERT INTO EXPERIENCE VALUES ( 123 ,'Database Administrator' ,4 ,11);
INSERT INTO EXPERIENCE VALUES ( 123 ,'Production support and project DBA' ,2 ,9);
INSERT INTO EXPERIENCE VALUES ( 123 ,'Technical Assurance Coordinator' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 124 ,'Science and Engineering Teacher' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 124 ,'Principal Engineer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 125 ,'Senior Software Developer' ,0 ,1595);
INSERT INTO EXPERIENCE VALUES ( 125 ,'Senior Software Engineer' ,4 ,1654);
INSERT INTO EXPERIENCE VALUES ( 125 ,'Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 126 ,'Senior Computer/Software Engineer' ,11 ,1661);
INSERT INTO EXPERIENCE VALUES ( 127 ,'Software Engineer' ,2 ,1652);
INSERT INTO EXPERIENCE VALUES ( 127 ,'Senior Technician' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 127 ,'senior student technician' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 127 ,'Software Engineer Intern' ,0 ,1650);
INSERT INTO EXPERIENCE VALUES ( 128 ,'Software Engineer (Intern)' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 128 ,'Academic Internship' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 129 ,'SOFTWARE DEVELOPER' ,2 ,1597);
INSERT INTO EXPERIENCE VALUES ( 129 ,'JUNIOR SOFTWARE DEVELOPER' ,0 ,1595);
INSERT INTO EXPERIENCE VALUES ( 130 ,'Web Developer' ,1 ,1306);
INSERT INTO EXPERIENCE VALUES ( 130 ,'Software Engineer' ,0 ,1650);
INSERT INTO EXPERIENCE VALUES ( 130 ,'Systems Analyst/Programmer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 130 ,'IT Consultant' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 130 ,'Corporate Development Intern' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 132 ,'Office Administrator/Manager' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 132 ,'Administrative and Customer Service Professional' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 132 ,'Badenock and Clerk Recruitment' ,-2 ,-2);
INSERT INTO EXPERIENCE VALUES ( 132 ,'Temporary Employee' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 132 ,'Office Manager/Administrator' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 132 ,'Purchasing Stock Control' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 132 ,'Pre-Despatch Inspection' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 133 ,'Senior Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 133 ,'Senior Solution Engineer' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 134 ,'Senior Software Engineer' ,2 ,1652);
INSERT INTO EXPERIENCE VALUES ( 134 ,'Senior Software Engineer' ,4 ,1654);
INSERT INTO EXPERIENCE VALUES ( 134 ,'Principal Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 134 ,'Software Engineer' ,0 ,1650);
INSERT INTO EXPERIENCE VALUES ( 134 ,'Team Lead' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 135 ,'Programmer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 135 ,'Dietary Aide' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 135 ,'Warehouse Associate' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 135 ,'data entry' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 136 ,'TEST ANALYST' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 136 ,'TEST ENGINEER' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 136 ,'TECHNICAL SUPPORT EXECUTIVE' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 137 ,'Java Developer' ,2 ,1452);
INSERT INTO EXPERIENCE VALUES ( 138 ,'Air Resource Engineer Range D, Mechanical Professional Engineer' ,24 ,24);
INSERT INTO EXPERIENCE VALUES ( 138 ,'Technical Manager, all analysis' ,11 ,11);
INSERT INTO EXPERIENCE VALUES ( 138 ,'Principal Investigator, Thermal Design and Test' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 139 ,'Java Developer' ,1 ,1451);
INSERT INTO EXPERIENCE VALUES ( 140 ,'Software Engineer II (Java Developer)' ,-2 ,240698);
INSERT INTO EXPERIENCE VALUES ( 141 ,'role of the Scrum Master' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 141 ,'Scrum Master' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 141 ,'Software Developer' ,4 ,1599);
INSERT INTO EXPERIENCE VALUES ( 141 ,'Design Engineer (Part-time)' ,-4 ,-4);
INSERT INTO EXPERIENCE VALUES ( 141 ,'Application Programmer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 142 ,'Software Developer' ,4 ,1599);
INSERT INTO EXPERIENCE VALUES ( 142 ,'Software Developer' ,4 ,1599);
INSERT INTO EXPERIENCE VALUES ( 142 ,'Java Programmer / Intern' ,1 ,11);
INSERT INTO EXPERIENCE VALUES ( 142 ,'Java Programmer / Intern' ,0 ,10);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Music Video Director' ,19 ,19);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Director' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Guest Director' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Floor Director' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Writer/Actor' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Program Developer' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Writer/Actor' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Creative Manager/Host/Actor' ,-1 ,-1);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Writer (GMA-New Media)' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Content writer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 143 ,'contributor' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 143 ,'Acting Workshop Facilitator and Trainor' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 144 ,'Programmer' ,9 ,9);
INSERT INTO EXPERIENCE VALUES ( 145 ,'Senior Software Engineer' ,7 ,1657);
INSERT INTO EXPERIENCE VALUES ( 146 ,'Test Analyst (Deputy Test Lead)' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 146 ,'IT Technician' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 147 ,'iOS DEVELOPER (SWIFT)' ,1 ,871);
INSERT INTO EXPERIENCE VALUES ( 148 ,'Software Developer' ,1 ,1596);
INSERT INTO EXPERIENCE VALUES ( 149 ,'Java Developer' ,1 ,1451);
INSERT INTO EXPERIENCE VALUES ( 149 ,'Developer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 150 ,'IT Support Technician' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 150 ,'Bootstrap Web Developer' ,1 ,1306);
INSERT INTO EXPERIENCE VALUES ( 150 ,'Wordpress Developer/intern' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 150 ,'Developing Apps' ,3 ,3);
INSERT INTO EXPERIENCE VALUES ( 150 ,'IT Specialist' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 152 ,'Software Developer' ,3 ,1598);
INSERT INTO EXPERIENCE VALUES ( 152 ,'Personal Care Assistant' ,2 ,2);
INSERT INTO EXPERIENCE VALUES ( 154 ,'Programmer' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 154 ,'Programmer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 154 ,'Computer Repair Technician' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 155 ,'Project Manager' ,3 ,3);
INSERT INTO EXPERIENCE VALUES ( 155 ,'Sales Representative' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 155 ,'New Car Sales Consultant' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 156 ,'Senior Software Engineer' ,3 ,1653);
INSERT INTO EXPERIENCE VALUES ( 156 ,'Senior Developer' ,2 ,2);
INSERT INTO EXPERIENCE VALUES ( 157 ,'Project Manager' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 157 ,'Manufacturing Engineer Manager' ,3 ,3);
INSERT INTO EXPERIENCE VALUES ( 157 ,'Head of Bussing and Expedition Staff' ,6 ,6);
INSERT INTO EXPERIENCE VALUES ( 157 ,'Project Leader' ,2 ,2);
INSERT INTO EXPERIENCE VALUES ( 157 ,'Quality Engineering Intern' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 157 ,'Project leader' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 157 ,'Project Leader' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 160 ,'Store Manager / Store Manager' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 160 ,'Sales Rep' ,3 ,3);
INSERT INTO EXPERIENCE VALUES ( 160 ,'Marketing Consultant' ,-3 ,-3);
INSERT INTO EXPERIENCE VALUES ( 161 ,'C# Programmer' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 161 ,'C# Programmer' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 161 ,'Vice President / Co-Founder' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 161 ,'Veterinary Technician' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 162 ,'Research Assistant' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 162 ,'Resident Assistant' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 163 ,'Developer' ,2 ,2);
INSERT INTO EXPERIENCE VALUES ( 163 ,'Jr. Web Developer' ,1 ,1306);
INSERT INTO EXPERIENCE VALUES ( 163 ,'Web Developer' ,1 ,1306);
INSERT INTO EXPERIENCE VALUES ( 163 ,'IS Support Intern' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 164 ,'Java Consultant' ,1 ,501);
INSERT INTO EXPERIENCE VALUES ( 164 ,'Software Developer' ,2 ,1597);
INSERT INTO EXPERIENCE VALUES ( 165 ,'Sr. Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 165 ,'Sr. Software Engineer' ,5 ,1655);
INSERT INTO EXPERIENCE VALUES ( 167 ,'Private Chef Services' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 167 ,'Sous Chef' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 167 ,'Sous Chef' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 169 ,'Project Manager' ,3 ,3);
INSERT INTO EXPERIENCE VALUES ( 169 ,'Capital Improvements' ,3 ,3);
INSERT INTO EXPERIENCE VALUES ( 170 ,'ICT and Computer Science Teacher' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 171 ,'Field EPOS Engineer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 171 ,'Installation Engineer' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 172 ,'iOS Developer' ,0 ,870);
INSERT INTO EXPERIENCE VALUES ( 173 ,'Software Engineer / Service Desk' ,4 ,1654);
INSERT INTO EXPERIENCE VALUES ( 173 ,'Human Resources Trainee' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 173 ,'Insurance Agent Trainee' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 173 ,'Volunteer' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 173 ,'Volunteer' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 174 ,'Data Analyst / Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 174 ,'Teacher Assistant' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 174 ,'Software Engineering Intern' ,0 ,1650);
INSERT INTO EXPERIENCE VALUES ( 174 ,'Hardware Design Intern' ,0 ,8);
INSERT INTO EXPERIENCE VALUES ( 177 ,'Web Developer' ,0 ,1305);
INSERT INTO EXPERIENCE VALUES ( 177 ,'Math Tutor' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 179 ,'Senior Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Programme Director' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Cloud Modern Platform Programme Director' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Programme Director' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Technical Refresh Programme Director' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Account Delivery Operations Manager' ,2 ,2);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Account Manager / Delivery Manager' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Programme Manager' ,2 ,2);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Programme Manager' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Senior Project Manager' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Senior Project Manager' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 180 ,'Project Manager' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 180 ,'CHIEF PETTY OFFICER' ,20 ,20);
INSERT INTO EXPERIENCE VALUES ( 181 ,'IT Support Technician' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 182 ,'Senior Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 182 ,'Software Engineer' ,5 ,1655);
INSERT INTO EXPERIENCE VALUES ( 183 ,'Hardware Sales Associate' ,0 ,8);
INSERT INTO EXPERIENCE VALUES ( 183 ,'Composite Technician' ,2 ,2);
INSERT INTO EXPERIENCE VALUES ( 183 ,'Rural Carrier Associate' ,3 ,3);
INSERT INTO EXPERIENCE VALUES ( 183 ,'Instructor' ,10 ,10);
INSERT INTO EXPERIENCE VALUES ( 183 ,'Internship' ,-8 ,-8);
INSERT INTO EXPERIENCE VALUES ( 183 ,'Student Researcher' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 183 ,'Quality Assurance Inspector' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 184 ,'WEB DEVELOPER' ,0 ,1305);
INSERT INTO EXPERIENCE VALUES ( 184 ,'GAME DEVELOPER' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 184 ,'DEVELOPER' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 184 ,'INFORMATIC ASSISTANT AND FREE COURSES TEACHER' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 185 ,'Technical Support - Troubleshooting IOS' ,0 ,6);
INSERT INTO EXPERIENCE VALUES ( 186 ,'Research Assistant' ,0 ,0);
INSERT INTO EXPERIENCE VALUES ( 187 ,'Research Assistant' ,6 ,6);
INSERT INTO EXPERIENCE VALUES ( 190 ,'I.T. Consultant' ,11 ,11);
INSERT INTO EXPERIENCE VALUES ( 191 ,'Software Developer' ,2 ,1597);
INSERT INTO EXPERIENCE VALUES ( 191 ,'Senior Release Engineer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 191 ,'Senior Release Engineer' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 191 ,'Software Quality Engineer' ,0 ,1650);
INSERT INTO EXPERIENCE VALUES ( 191 ,'Senior Software Test Engineer' ,8 ,1658);
INSERT INTO EXPERIENCE VALUES ( 192 ,'Software Engineer' ,2 ,1652);
INSERT INTO EXPERIENCE VALUES ( 192 ,'Software Engineer' ,1 ,1651);
INSERT INTO EXPERIENCE VALUES ( 193 ,'Project Manager' ,4 ,4);
INSERT INTO EXPERIENCE VALUES ( 195 ,'Software Developer' ,1 ,1596);
INSERT INTO EXPERIENCE VALUES ( 195 ,'Android and Front-end Web Developer' ,0 ,1305);
INSERT INTO EXPERIENCE VALUES ( 195 ,'Startups - Web Developer' ,1 ,1306);
INSERT INTO EXPERIENCE VALUES ( 195 ,'Web Developer' ,1 ,1306);
INSERT INTO EXPERIENCE VALUES ( 196 ,'SENIOR SOFTWARE ENGINEER' ,6 ,1656);
INSERT INTO EXPERIENCE VALUES ( 197 ,'Programmer' ,1 ,1);
INSERT INTO EXPERIENCE VALUES ( 197 ,'Database Developer' ,6 ,1021);
INSERT INTO EXPERIENCE VALUES ( 197 ,'General Manager' ,2 ,2);
INSERT INTO STUDIES VALUES ( 101 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 102 ,4 ,0 ,400);
INSERT INTO STUDIES VALUES ( 103 ,0 ,3 ,3);
INSERT INTO STUDIES VALUES ( 104 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 105 ,4 ,2 ,402);
INSERT INTO STUDIES VALUES ( 106 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 107 ,0 ,4 ,4);
INSERT INTO STUDIES VALUES ( 108 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 109 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 110 ,0 ,5 ,5);
INSERT INTO STUDIES VALUES ( 111 ,0 ,9 ,9);
INSERT INTO STUDIES VALUES ( 112 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 113 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 114 ,6 ,3 ,603);
INSERT INTO STUDIES VALUES ( 115 ,0 ,2 ,2);
INSERT INTO STUDIES VALUES ( 116 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 117 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 118 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 119 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 120 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 121 ,0 ,4 ,4);
INSERT INTO STUDIES VALUES ( 122 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 123 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 124 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 125 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 126 ,4 ,0 ,400);
INSERT INTO STUDIES VALUES ( 127 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 128 ,0 ,6 ,6);
INSERT INTO STUDIES VALUES ( 129 ,0 ,4 ,4);
INSERT INTO STUDIES VALUES ( 130 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 131 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 132 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 133 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 134 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 135 ,0 ,1 ,1);
INSERT INTO STUDIES VALUES ( 136 ,0 ,5 ,5);
INSERT INTO STUDIES VALUES ( 137 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 138 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 139 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 140 ,0 ,2 ,2);
INSERT INTO STUDIES VALUES ( 141 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 142 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 143 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 144 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 145 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 146 ,0 ,2 ,2);
INSERT INTO STUDIES VALUES ( 147 ,2 ,0 ,200);
INSERT INTO STUDIES VALUES ( 148 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 149 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 150 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 151 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 152 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 153 ,0 ,5 ,5);
INSERT INTO STUDIES VALUES ( 154 ,0 ,5 ,5);
INSERT INTO STUDIES VALUES ( 155 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 156 ,4 ,1 ,401);
INSERT INTO STUDIES VALUES ( 157 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 158 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 159 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 160 ,0 ,8 ,8);
INSERT INTO STUDIES VALUES ( 161 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 162 ,0 ,8 ,8);
INSERT INTO STUDIES VALUES ( 163 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 164 ,0 ,2 ,2);
INSERT INTO STUDIES VALUES ( 165 ,4 ,0 ,400);
INSERT INTO STUDIES VALUES ( 166 ,0 ,6 ,6);
INSERT INTO STUDIES VALUES ( 167 ,2 ,4 ,204);
INSERT INTO STUDIES VALUES ( 168 ,0 ,6 ,6);
INSERT INTO STUDIES VALUES ( 169 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 170 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 171 ,0 ,3 ,3);
INSERT INTO STUDIES VALUES ( 172 ,0 ,9 ,9);
INSERT INTO STUDIES VALUES ( 173 ,0 ,9 ,9);
INSERT INTO STUDIES VALUES ( 174 ,4 ,9 ,409);
INSERT INTO STUDIES VALUES ( 175 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 176 ,0 ,5 ,5);
INSERT INTO STUDIES VALUES ( 177 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 178 ,0 ,5 ,5);
INSERT INTO STUDIES VALUES ( 179 ,6 ,0 ,600);
INSERT INTO STUDIES VALUES ( 180 ,0 ,2 ,2);
INSERT INTO STUDIES VALUES ( 181 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 182 ,0 ,2 ,2);
INSERT INTO STUDIES VALUES ( 183 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 184 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 185 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 186 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 187 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 188 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 189 ,0 ,2 ,2);
INSERT INTO STUDIES VALUES ( 190 ,0 ,3 ,3);
INSERT INTO STUDIES VALUES ( 191 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 192 ,0 ,2 ,2);
INSERT INTO STUDIES VALUES ( 193 ,0 ,1 ,1);
INSERT INTO STUDIES VALUES ( 194 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 195 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 196 ,0 ,0 ,0);
INSERT INTO STUDIES VALUES ( 197 ,0 ,4 ,4);
INSERT INTO STUDIES VALUES ( 198 ,0 ,0 ,0);
INSERT INTO SOFTSKILLS VALUES ( 174 ,'Business Analysis' ,5);
INSERT INTO SOFTSKILLS VALUES ( 174 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 174 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 176 ,'Accounting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 176 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 176 ,'Reliability' ,2);
INSERT INTO SOFTSKILLS VALUES ( 178 ,'Customer Service' ,5);
INSERT INTO SOFTSKILLS VALUES ( 178 ,'customer service skills' ,5);
INSERT INTO SOFTSKILLS VALUES ( 178 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 178 ,'Planning' ,6);
INSERT INTO SOFTSKILLS VALUES ( 178 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 178 ,'Project Planning' ,13);
INSERT INTO SOFTSKILLS VALUES ( 179 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 179 ,'Decision Support Systems (DSS)' ,1);
INSERT INTO SOFTSKILLS VALUES ( 179 ,'Entrepreneurship' ,3);
INSERT INTO SOFTSKILLS VALUES ( 179 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 179 ,'Planning' ,6);
INSERT INTO SOFTSKILLS VALUES ( 179 ,'Risk Analysis' ,6);
INSERT INTO SOFTSKILLS VALUES ( 179 ,'Risk Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 180 ,'Account Management' ,8);
INSERT INTO SOFTSKILLS VALUES ( 180 ,'Account Manager' ,5);
INSERT INTO SOFTSKILLS VALUES ( 180 ,'HR' ,7);
INSERT INTO SOFTSKILLS VALUES ( 180 ,'Human Resources' ,7);
INSERT INTO SOFTSKILLS VALUES ( 180 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 180 ,'Project Closure' ,7);
INSERT INTO SOFTSKILLS VALUES ( 180 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 180 ,'Project Manager' ,7);
INSERT INTO SOFTSKILLS VALUES ( 180 ,'Senior Project Manager' ,7);
INSERT INTO SOFTSKILLS VALUES ( 180 ,'Strong Leader' ,7);
INSERT INTO SOFTSKILLS VALUES ( 181 ,'Help Desk' ,4);
INSERT INTO SOFTSKILLS VALUES ( 181 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 181 ,'Technical Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 182 ,'Accounting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 182 ,'Accounting Software' ,5);
INSERT INTO SOFTSKILLS VALUES ( 182 ,'Asset Management' ,8);
INSERT INTO SOFTSKILLS VALUES ( 182 ,'Buying' ,3);
INSERT INTO SOFTSKILLS VALUES ( 182 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 182 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 182 ,'Project Manager' ,7);
INSERT INTO SOFTSKILLS VALUES ( 183 ,'Sales Support' ,2);
INSERT INTO SOFTSKILLS VALUES ( 183 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 184 ,'Data Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 184 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 184 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 184 ,'Technical Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 185 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 185 ,'Technical Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 186 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 186 ,'Excellent Communication Skills' ,16);
INSERT INTO SOFTSKILLS VALUES ( 186 ,'Excellent Problem Solving Skills' ,18);
INSERT INTO SOFTSKILLS VALUES ( 186 ,'Problem Solving' ,6);
INSERT INTO SOFTSKILLS VALUES ( 186 ,'Problem Solving Skills' ,12);
INSERT INTO SOFTSKILLS VALUES ( 186 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 186 ,'Technical Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 188 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 188 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 188 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 188 ,'Risk Assessment' ,6);
INSERT INTO SOFTSKILLS VALUES ( 188 ,'SCRUM' ,6);
INSERT INTO SOFTSKILLS VALUES ( 188 ,'Statistical Analysis' ,6);
INSERT INTO SOFTSKILLS VALUES ( 188 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 190 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 191 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 191 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 191 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 191 ,'SCRUM' ,6);
INSERT INTO SOFTSKILLS VALUES ( 191 ,'Scrum Master' ,13);
INSERT INTO SOFTSKILLS VALUES ( 191 ,'Statistical Analysis' ,6);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Accounting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Business Analysis' ,5);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Business Requirements' ,5);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Call Center' ,4);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Planning' ,6);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Problem Solving' ,6);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Problem Solving Skills' ,12);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Project Manager' ,7);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Verbal Communication' ,8);
INSERT INTO SOFTSKILLS VALUES ( 193 ,'Verbal Communication Skills' ,24);
INSERT INTO SOFTSKILLS VALUES ( 194 ,'Advertising' ,5);
INSERT INTO SOFTSKILLS VALUES ( 196 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 196 ,'Confluence' ,4);
INSERT INTO SOFTSKILLS VALUES ( 196 ,'SCRUM' ,6);
INSERT INTO SOFTSKILLS VALUES ( 196 ,'Statistics' ,4);
INSERT INTO SOFTSKILLS VALUES ( 198 ,'Team Player' ,7);
INSERT INTO SOFTSKILLS VALUES ( 101 ,'PC Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 101 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 102 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 102 ,'People Management' ,9);
INSERT INTO SOFTSKILLS VALUES ( 103 ,'Analytical Skills' ,5);
INSERT INTO SOFTSKILLS VALUES ( 103 ,'Business Management' ,9);
INSERT INTO SOFTSKILLS VALUES ( 103 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 104 ,'Audit' ,6);
INSERT INTO SOFTSKILLS VALUES ( 105 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Agile Methodologies' ,13);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Agile methodology' ,13);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Budgeting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Full Project Lifecycle' ,5);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Planning' ,6);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Program Management' ,9);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Project Manager' ,7);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Resource Management' ,9);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Risk Assessment' ,6);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Strategic Planning' ,12);
INSERT INTO SOFTSKILLS VALUES ( 106 ,'Vendor Management' ,8);
INSERT INTO SOFTSKILLS VALUES ( 107 ,'Assessments' ,5);
INSERT INTO SOFTSKILLS VALUES ( 107 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 107 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 108 ,'Desk Top Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 109 ,'Code Review' ,7);
INSERT INTO SOFTSKILLS VALUES ( 113 ,'Advertising' ,5);
INSERT INTO SOFTSKILLS VALUES ( 113 ,'Call Center' ,4);
INSERT INTO SOFTSKILLS VALUES ( 113 ,'Customer Service' ,5);
INSERT INTO SOFTSKILLS VALUES ( 113 ,'Planning' ,6);
INSERT INTO SOFTSKILLS VALUES ( 113 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 113 ,'Technical Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 115 ,'Accounting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 115 ,'Accounts Receivable' ,5);
INSERT INTO SOFTSKILLS VALUES ( 115 ,'Agile Methodologies' ,13);
INSERT INTO SOFTSKILLS VALUES ( 115 ,'Agile methodology' ,13);
INSERT INTO SOFTSKILLS VALUES ( 116 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 116 ,'Multithreading' ,7);
INSERT INTO SOFTSKILLS VALUES ( 116 ,'SCRUM' ,6);
INSERT INTO SOFTSKILLS VALUES ( 117 ,'Accounting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 117 ,'Business Requirements' ,5);
INSERT INTO SOFTSKILLS VALUES ( 118 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 118 ,'SCRUM' ,6);
INSERT INTO SOFTSKILLS VALUES ( 118 ,'Scrum Master' ,13);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Accounting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Asset Management' ,8);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Budgeting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Business Management' ,9);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Change Management' ,7);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Configuration Management' ,8);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Enterprise Resource Planning' ,6);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'HR' ,7);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Human Resources' ,7);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Microsoft Change Management' ,7);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Planning' ,6);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Problem Solving' ,6);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 121 ,'System Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 122 ,'Error Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 122 ,'Global System for Mobile Communications (GSM)' ,8);
INSERT INTO SOFTSKILLS VALUES ( 122 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 123 ,'Accounting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 123 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 123 ,'Problem Solving' ,6);
INSERT INTO SOFTSKILLS VALUES ( 123 ,'Problem Solving Skills' ,12);
INSERT INTO SOFTSKILLS VALUES ( 123 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 124 ,'Business Management' ,9);
INSERT INTO SOFTSKILLS VALUES ( 124 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 124 ,'Management Trainee' ,5);
INSERT INTO SOFTSKILLS VALUES ( 124 ,'Project Leader' ,7);
INSERT INTO SOFTSKILLS VALUES ( 124 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 125 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 125 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 126 ,'Associate in Risk Management' ,9);
INSERT INTO SOFTSKILLS VALUES ( 126 ,'Attention to Detail' ,8);
INSERT INTO SOFTSKILLS VALUES ( 126 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 126 ,'Configuration Management' ,8);
INSERT INTO SOFTSKILLS VALUES ( 126 ,'Confluence' ,4);
INSERT INTO SOFTSKILLS VALUES ( 126 ,'Focus' ,5);
INSERT INTO SOFTSKILLS VALUES ( 126 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 126 ,'Planning' ,6);
INSERT INTO SOFTSKILLS VALUES ( 126 ,'PVCS Tracker (defect tracking and management tool)' ,3);
INSERT INTO SOFTSKILLS VALUES ( 126 ,'Requirements Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 128 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 130 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 130 ,'Entrepreneurship' ,3);
INSERT INTO SOFTSKILLS VALUES ( 130 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 130 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 130 ,'SCRUM' ,6);
INSERT INTO SOFTSKILLS VALUES ( 131 ,'Business Development' ,5);
INSERT INTO SOFTSKILLS VALUES ( 131 ,'Business Development Manager' ,11);
INSERT INTO SOFTSKILLS VALUES ( 131 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 131 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 131 ,'Recruiter' ,7);
INSERT INTO SOFTSKILLS VALUES ( 131 ,'Strategic Vision' ,4);
INSERT INTO SOFTSKILLS VALUES ( 131 ,'Written Communication' ,8);
INSERT INTO SOFTSKILLS VALUES ( 131 ,'Written Communication Skills' ,24);
INSERT INTO SOFTSKILLS VALUES ( 132 ,'Accounts Payable' ,5);
INSERT INTO SOFTSKILLS VALUES ( 132 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 132 ,'Customer Accounts' ,5);
INSERT INTO SOFTSKILLS VALUES ( 132 ,'Customer Service' ,5);
INSERT INTO SOFTSKILLS VALUES ( 132 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 132 ,'Staffing and Recruitment' ,5);
INSERT INTO SOFTSKILLS VALUES ( 132 ,'Verbal Communication' ,8);
INSERT INTO SOFTSKILLS VALUES ( 132 ,'Verbal Communication Skills' ,24);
INSERT INTO SOFTSKILLS VALUES ( 133 ,'Accounting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 133 ,'Accounting Software' ,5);
INSERT INTO SOFTSKILLS VALUES ( 133 ,'Financials' ,1);
INSERT INTO SOFTSKILLS VALUES ( 133 ,'Gathering Requirements' ,3);
INSERT INTO SOFTSKILLS VALUES ( 133 ,'Generally accepted accounting principles' ,11);
INSERT INTO SOFTSKILLS VALUES ( 133 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 133 ,'Monthly Financial Statements' ,2);
INSERT INTO SOFTSKILLS VALUES ( 133 ,'Peachtree Accounting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'Coaching' ,4);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'Excellent Communication Skills' ,16);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'Global System for Mobile Communications (GSM)' ,8);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'Problem Solving' ,6);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'SCRUM' ,6);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'Scrum Master' ,13);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 134 ,'Team Lead' ,7);
INSERT INTO SOFTSKILLS VALUES ( 136 ,'Customer Service' ,5);
INSERT INTO SOFTSKILLS VALUES ( 136 ,'Global System for Mobile Communications (GSM)' ,8);
INSERT INTO SOFTSKILLS VALUES ( 136 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 136 ,'Reliability' ,2);
INSERT INTO SOFTSKILLS VALUES ( 136 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 136 ,'Technical Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 136 ,'Telecommunications' ,8);
INSERT INTO SOFTSKILLS VALUES ( 137 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 137 ,'Agile Methodologies' ,13);
INSERT INTO SOFTSKILLS VALUES ( 137 ,'Agile methodology' ,13);
INSERT INTO SOFTSKILLS VALUES ( 137 ,'Corporate Training' ,6);
INSERT INTO SOFTSKILLS VALUES ( 137 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 137 ,'Reviews' ,2);
INSERT INTO SOFTSKILLS VALUES ( 137 ,'SCRUM' ,6);
INSERT INTO SOFTSKILLS VALUES ( 137 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 139 ,'Analytical Skills' ,5);
INSERT INTO SOFTSKILLS VALUES ( 139 ,'Code Review' ,7);
INSERT INTO SOFTSKILLS VALUES ( 139 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 140 ,'Account Management' ,8);
INSERT INTO SOFTSKILLS VALUES ( 140 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 140 ,'Confluence' ,4);
INSERT INTO SOFTSKILLS VALUES ( 140 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 140 ,'Synchronous Transport Signal (STS)' ,7);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'Application Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'Audit' ,6);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'Confluence' ,4);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'Document Management' ,8);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'Excellent Communication Skills' ,16);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'SCRUM' ,6);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'Scrum Master' ,13);
INSERT INTO SOFTSKILLS VALUES ( 141 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 142 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 142 ,'End-user Training' ,6);
INSERT INTO SOFTSKILLS VALUES ( 142 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 142 ,'Requirements Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 144 ,'Customer Service' ,5);
INSERT INTO SOFTSKILLS VALUES ( 144 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 145 ,'Configuration Management' ,8);
INSERT INTO SOFTSKILLS VALUES ( 145 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 145 ,'Multithreading' ,7);
INSERT INTO SOFTSKILLS VALUES ( 146 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 146 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 146 ,'Technical Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 147 ,'Agile Methodologies' ,13);
INSERT INTO SOFTSKILLS VALUES ( 147 ,'Agile methodology' ,13);
INSERT INTO SOFTSKILLS VALUES ( 147 ,'Buying' ,3);
INSERT INTO SOFTSKILLS VALUES ( 147 ,'Code Review' ,7);
INSERT INTO SOFTSKILLS VALUES ( 147 ,'Data Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 147 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 147 ,'Multithreading' ,7);
INSERT INTO SOFTSKILLS VALUES ( 147 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 148 ,'Business Development' ,5);
INSERT INTO SOFTSKILLS VALUES ( 148 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 148 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 148 ,'Technical Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 149 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 149 ,'Agile Methodologies' ,13);
INSERT INTO SOFTSKILLS VALUES ( 149 ,'Agile Software Development' ,7);
INSERT INTO SOFTSKILLS VALUES ( 149 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 149 ,'Patch Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 149 ,'SCRUM' ,6);
INSERT INTO SOFTSKILLS VALUES ( 150 ,'Customer Accounts' ,5);
INSERT INTO SOFTSKILLS VALUES ( 150 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 150 ,'Technical Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 152 ,'Data Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 152 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 153 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 153 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 155 ,'Customer Relationship Management' ,7);
INSERT INTO SOFTSKILLS VALUES ( 155 ,'Customer Service' ,5);
INSERT INTO SOFTSKILLS VALUES ( 155 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 155 ,'Marketing Management' ,6);
INSERT INTO SOFTSKILLS VALUES ( 155 ,'Product Management' ,9);
INSERT INTO SOFTSKILLS VALUES ( 155 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 155 ,'Project Manager' ,7);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Accounting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Agile' ,7);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Business Development' ,5);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Confluence' ,4);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Equity' ,3);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Project Manager' ,7);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Telecommunications' ,8);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Written Communication' ,8);
INSERT INTO SOFTSKILLS VALUES ( 156 ,'Written Communication Skills' ,24);
INSERT INTO SOFTSKILLS VALUES ( 157 ,'Associate in Risk Management' ,9);
INSERT INTO SOFTSKILLS VALUES ( 157 ,'Consulting' ,4);
INSERT INTO SOFTSKILLS VALUES ( 157 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 157 ,'Project Leader' ,7);
INSERT INTO SOFTSKILLS VALUES ( 157 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 157 ,'Project Manager' ,7);
INSERT INTO SOFTSKILLS VALUES ( 158 ,'Administrative Assistant' ,4);
INSERT INTO SOFTSKILLS VALUES ( 158 ,'Audit' ,6);
INSERT INTO SOFTSKILLS VALUES ( 158 ,'Business Development' ,5);
INSERT INTO SOFTSKILLS VALUES ( 158 ,'Consulting' ,4);
INSERT INTO SOFTSKILLS VALUES ( 158 ,'Financials' ,1);
INSERT INTO SOFTSKILLS VALUES ( 158 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 158 ,'New Business Development' ,8);
INSERT INTO SOFTSKILLS VALUES ( 159 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 159 ,'Technical Lead' ,6);
INSERT INTO SOFTSKILLS VALUES ( 160 ,'Advertising' ,5);
INSERT INTO SOFTSKILLS VALUES ( 160 ,'Complaints' ,4);
INSERT INTO SOFTSKILLS VALUES ( 160 ,'Marketing Management' ,6);
INSERT INTO SOFTSKILLS VALUES ( 163 ,'Assessments' ,5);
INSERT INTO SOFTSKILLS VALUES ( 163 ,'Code Review' ,7);
INSERT INTO SOFTSKILLS VALUES ( 163 ,'Confluence' ,4);
INSERT INTO SOFTSKILLS VALUES ( 163 ,'Consulting' ,4);
INSERT INTO SOFTSKILLS VALUES ( 163 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 164 ,'Business Requirements' ,5);
INSERT INTO SOFTSKILLS VALUES ( 164 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 165 ,'Agile Methodologies' ,13);
INSERT INTO SOFTSKILLS VALUES ( 165 ,'Agile methodology' ,13);
INSERT INTO SOFTSKILLS VALUES ( 165 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 165 ,'Consulting' ,4);
INSERT INTO SOFTSKILLS VALUES ( 165 ,'Corporate Training' ,6);
INSERT INTO SOFTSKILLS VALUES ( 165 ,'Planning' ,6);
INSERT INTO SOFTSKILLS VALUES ( 165 ,'Reviews' ,2);
INSERT INTO SOFTSKILLS VALUES ( 165 ,'Written Communication' ,8);
INSERT INTO SOFTSKILLS VALUES ( 165 ,'Written Communication Skills' ,24);
INSERT INTO SOFTSKILLS VALUES ( 166 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 167 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 168 ,'Simple Network Management Protocol' ,3);
INSERT INTO SOFTSKILLS VALUES ( 169 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 169 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 169 ,'Project Manager' ,7);
INSERT INTO SOFTSKILLS VALUES ( 170 ,'Budgeting' ,5);
INSERT INTO SOFTSKILLS VALUES ( 170 ,'Business Development' ,5);
INSERT INTO SOFTSKILLS VALUES ( 170 ,'Business Development Manager' ,11);
INSERT INTO SOFTSKILLS VALUES ( 170 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 170 ,'Marketing Management' ,6);
INSERT INTO SOFTSKILLS VALUES ( 170 ,'Project Management' ,10);
INSERT INTO SOFTSKILLS VALUES ( 170 ,'Recruiting' ,7);
INSERT INTO SOFTSKILLS VALUES ( 170 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 170 ,'Telecommunications' ,8);
INSERT INTO SOFTSKILLS VALUES ( 171 ,'Communications' ,8);
INSERT INTO SOFTSKILLS VALUES ( 171 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 171 ,'Support' ,1);
INSERT INTO SOFTSKILLS VALUES ( 171 ,'Telecommunications' ,8);
INSERT INTO SOFTSKILLS VALUES ( 172 ,'Data Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 172 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 173 ,'Communication Skills' ,8);
INSERT INTO SOFTSKILLS VALUES ( 173 ,'Human Resources' ,7);
INSERT INTO SOFTSKILLS VALUES ( 173 ,'Management' ,3);
INSERT INTO SOFTSKILLS VALUES ( 173 ,'Product Management' ,9);
INSERT INTO SOFTSKILLS VALUES ( 174 ,'Budgeting' ,5);
INSERT INTO TECHNICALSKILLS VALUES ( 195 ,'CakePHP' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 195 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 195 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 195 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 196 ,'Java 2 Enterprise Edition (J2EE)' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 196 ,'Java Message Service' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 196 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 196 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 197 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 197 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 198 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 101 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 101 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 101 ,'C/C++ Programming Languages' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 101 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 101 ,'Java Swing' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 102 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 102 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 104 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 104 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 104 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 105 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 105 ,'C/C++ Programming Languages' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 105 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 105 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 105 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 105 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 106 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 106 ,'Java Technologies' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 107 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 108 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 108 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 108 ,'C/C++ Programming Languages' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 109 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 110 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 110 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 111 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 111 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 112 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 112 ,'C#.NET' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 112 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 112 ,'C/C++ Programming Languages' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 112 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 112 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 114 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 114 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'Enterprise Java Beans' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'Java 2 Enterprise Edition (J2EE)' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'Java Beans' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'JavaServer Faces' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'Microsoft Visual C++' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 115 ,'Visual Basic' ,14);
INSERT INTO TECHNICALSKILLS VALUES ( 118 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 118 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 119 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 120 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 120 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 120 ,'C/C++ Programming Languages' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 120 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 120 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 120 ,'Microsoft Visual Basic for Applications' ,14);
INSERT INTO TECHNICALSKILLS VALUES ( 120 ,'Microsoft Visual C++' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 122 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 122 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 122 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 124 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 125 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 125 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 125 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 126 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 126 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 126 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 126 ,'Microsoft Visual Basic for Applications' ,14);
INSERT INTO TECHNICALSKILLS VALUES ( 127 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 127 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 128 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 128 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 129 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 129 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 129 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 129 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 129 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 130 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 130 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 133 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 133 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 133 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 133 ,'Microsoft Visual Basic for Applications' ,14);
INSERT INTO TECHNICALSKILLS VALUES ( 133 ,'Visual Basic' ,14);
INSERT INTO TECHNICALSKILLS VALUES ( 134 ,'Java Persistence API' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 134 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 134 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 134 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 136 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 136 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 137 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 137 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 137 ,'Java Technologies' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 138 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 139 ,'Java 2 Enterprise Edition (J2EE)' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 139 ,'Java Beans' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 139 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 139 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 139 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 139 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 140 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 140 ,'Java 2 Enterprise Edition (J2EE)' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 140 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 140 ,'Java Technologies' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 140 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 141 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 141 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 141 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 141 ,'Visual Basic' ,14);
INSERT INTO TECHNICALSKILLS VALUES ( 142 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 142 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 142 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 142 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 142 ,'JavaServer Faces' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 142 ,'PHP Frameworks' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 142 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 144 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 144 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 145 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 145 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 145 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 145 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 145 ,'Microsoft Visual C++' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 147 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 148 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 149 ,'Java 2 Enterprise Edition (J2EE)' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 149 ,'Java Message Service' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 149 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 149 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 149 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 150 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 150 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 151 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 151 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 151 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 151 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 151 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 152 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 152 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 153 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 154 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 154 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 154 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 154 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 156 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 156 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 156 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 156 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 156 ,'Visual Basic' ,14);
INSERT INTO TECHNICALSKILLS VALUES ( 157 ,'Microsoft Visual Basic for Applications' ,14);
INSERT INTO TECHNICALSKILLS VALUES ( 159 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 159 ,'Java 2 Enterprise Edition (J2EE)' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 159 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 159 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 161 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 162 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 162 ,'C/C++ Programming Languages' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 162 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 162 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 162 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 163 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 163 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 163 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 164 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 164 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 164 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 165 ,'Java Message Service' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 165 ,'Java Persistence API' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 165 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 165 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 166 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 166 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 166 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 166 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 168 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 168 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 172 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 174 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 174 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 174 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 174 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 174 ,'Visual Basic' ,14);
INSERT INTO TECHNICALSKILLS VALUES ( 175 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 175 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 175 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 177 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 177 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 177 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 177 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 178 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 178 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 178 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 178 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 178 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 178 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 179 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 181 ,'C/C++ Programming Languages' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 181 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 182 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 182 ,'C/C++ Programming Languages' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 182 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 182 ,'Java Server Pages' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 182 ,'Java Technologies' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 182 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 184 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 184 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 184 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 184 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 184 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 186 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 186 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 186 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 186 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 186 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 187 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 187 ,'C/C++ Programming Languages' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 187 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 187 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 188 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 188 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 188 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 188 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 188 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 189 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 189 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 189 ,'PHP Programming Language' ,16);
INSERT INTO TECHNICALSKILLS VALUES ( 191 ,'C# Programming Language' ,19);
INSERT INTO TECHNICALSKILLS VALUES ( 191 ,'C++ Programming Language' ,20);
INSERT INTO TECHNICALSKILLS VALUES ( 191 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 191 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 192 ,'Java Programming Language' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 192 ,'Java Swing' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 192 ,'Javascript' ,17);
INSERT INTO TECHNICALSKILLS VALUES ( 192 ,'Microsoft Visual Basic for Applications' ,14);
INSERT INTO TECHNICALSKILLS VALUES ( 192 ,'Python Programming Language' ,15);
INSERT INTO TECHNICALSKILLS VALUES ( 195 ,'C# Programming Language' ,19);
