create table CURRICULUMVITAE(
ID NUMBER,
CLUSTER_ID VARCHAR2(500),
NAME VARCHAR2(500),
DATE_OF_BIRTH DATE,
ADDRESS VARCHAR2(500),
PHONE_NUMBER NUMBER,
EMAIL VARCHAR2(500),
EXPERIENCE_YEARS NUMBER,
IDEAL_JOB VARCHAR2(500)
);
/
create table EXPERIENCE(
CV_ID NUMBER,
JOB_TITLE VARCHAR2(500),
EXPERIENCE_YEARS NUMBER,
VALUE NUMBER
);
/
create table STUDIES(
CV_ID NUMBER,
CERTIFICATE NUMBER,
STUDY_YEARS NUMBER,
VALUE NUMBER
);
/
create table SOFTSKILLS(
CV_ID NUMBER,
SKILL CLOB,
VALUE NUMBER
);
/
create table TECHNICALSKILLS(
CV_ID NUMBER,
SKILL CLOB,
VALUE NUMBER
);
/
create table CLUSTERING(
CLUSTER_ID NUMBER,
CENTER_OF_GRAVITY NUMBER
);
/

alter table CURRICULUMVITAE add constraint SYS_C0011398 primary key (ID); 
/

alter table EXPERIENCE add constraint FK_EXP foreign key (CV_ID) references CURRICULUMVITAE (ID); 
/
alter table STUDIES add constraint FK_STD foreign key (CV_ID) references CURRICULUMVITAE (ID); 
/
alter table SOFTSKILLS add constraint FK_SSK foreign key (CV_ID) references CURRICULUMVITAE (ID); 
/
alter table TECHNICALSKILLS add constraint FK_TSK foreign key (CV_ID) references CURRICULUMVITAE (ID); 
/

